const express=require('express');const http=require('http');const https=require('https');const crypto=require('crypto');const{Server}=require('socket.io');const app=express();const server=http.createServer(app);const allowedOriginsEnv=(process.env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean);const corsOrigin=allowedOriginsEnv.length?allowedOriginsEnv:'*';const io=new Server(server,{cors:{origin:corsOrigin,methods:['GET','POST']},maxHttpBufferSize:512*1024,pingInterval:10000,pingTimeout:8000});const PORT=process.env.PORT||3000;const rooms=new Map();const MAX_ROOMS=20000;const CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';function genRoomCode(){let code;do{code='';for(let i=0;i<5;i++)code+=CODE_CHARS[crypto.randomInt(CODE_CHARS.length)]}while(rooms.has(code));return code}
const VALID_MODES=['2p','4p','hunter'];function normalizeMode(mode){return VALID_MODES.includes(mode)?mode:'2p'}
function maxPlayersForMode(mode){return mode==='4p'?4:2}
const MAX_PAYLOAD_BYTES=100*1024;function payloadSizeOk(value){try{return Buffer.byteLength(JSON.stringify(value))<=MAX_PAYLOAD_BYTES}catch(e){return!0}}
function tokensMatch(a,b){if(typeof a!=='string'||typeof b!=='string')return!1;const bufA=Buffer.from(a);const bufB=Buffer.from(b);if(bufA.length!==bufB.length)return!1;return crypto.timingSafeEqual(bufA,bufB)}
function touch(room){room.lastActivity=Date.now()}
function presenceSnapshot(room){const out={};for(const slot in room.players){const p=room.players[slot];out[slot]={joinedAt:p.joinedAt,connected:p.connected}}
return out}
function broadcastPresence(code){const room=rooms.get(code);if(!room)return;io.to('room:'+code).emit('presence',presenceSnapshot(room))}
function assignSocketToSlot(socket,code,slot){socket.data.roomCode=code;socket.data.slot=slot;socket.join('room:'+code)}
function handleLeave(socket){const code=socket.data.roomCode;const slot=socket.data.slot;if(!code||slot===null||slot===undefined)return;const room=rooms.get(code);if(room&&room.players[slot]){if(room.players[slot].socketId===socket.id){room.players[slot].connected=!1;room.players[slot].leftAt=Date.now();touch(room)}}
socket.leave('room:'+code);socket.data.roomCode=null;socket.data.slot=null;if(room)broadcastPresence(code);}
const RATE_LIMIT_MAX=60;const RATE_LIMIT_WINDOW_MS=5000;function rateLimitOk(socket){const now=Date.now();const times=(socket.data.msgTimes||[]).filter(t=>now-t<RATE_LIMIT_WINDOW_MS);if(times.length>=RATE_LIMIT_MAX){socket.data.msgTimes=times;return!1}
times.push(now);socket.data.msgTimes=times;return!0}
const ROOM_OP_LIMIT_MAX=60;const ROOM_OP_LIMIT_WINDOW_MS=10000;function roomOpLimitOk(socket){const now=Date.now();const times=(socket.data.roomOpTimes||[]).filter(t=>now-t<ROOM_OP_LIMIT_WINDOW_MS);if(times.length>=ROOM_OP_LIMIT_MAX){socket.data.roomOpTimes=times;return!1}
times.push(now);socket.data.roomOpTimes=times;return!0}
function normalizeVisibility(v){return v==='private'?'private':'public'}
function openPublicRoomsList(){const list=[];for(const[code,room]of rooms.entries()){if(room.visibility!=='public')continue;const limit=room.maxPlayers||maxPlayersForMode(normalizeMode(room.mode));const connected=Object.values(room.players).filter(p=>p.connected).length;if(connected>=limit)continue;list.push({code,mode:room.mode,maxPlayers:limit,playerCount:connected,createdAt:room.createdAt})}
list.sort((a,b)=>b.createdAt-a.createdAt);return list.slice(0,50)}
io.on('connection',(socket)=>{socket.data.roomCode=null;socket.data.slot=null;socket.data.msgTimes=[];socket.data.roomOpTimes=[];socket.on('createRoom',({maxPlayers,mode,visibility}={},ack)=>{if(!roomOpLimitOk(socket)){if(ack)ack({ok:!1,error:'rate-limited'});return}
if(rooms.size>=MAX_ROOMS){if(ack)ack({ok:!1,error:'server-busy'});return}
const safeMode=normalizeMode(mode);const safeVisibility=normalizeVisibility(visibility);const code=genRoomCode();rooms.set(code,{maxPlayers:maxPlayersForMode(safeMode),mode:safeMode,visibility:safeVisibility,createdAt:Date.now(),lastActivity:Date.now(),seqBySlot:{},players:{},lastCheckpoint:null});if(ack)ack({ok:!0,code})});socket.on('roomExists',({code}={},ack)=>{if(!roomOpLimitOk(socket)){if(ack)ack({exists:!1,mode:null});return}
const room=rooms.get(String(code||'').slice(0,20).toUpperCase());if(ack)ack({exists:!!room,mode:room?room.mode:null})});socket.on('listPublicRooms',(_data,ack)=>{if(!roomOpLimitOk(socket)){if(ack)ack({rooms:[]});return}
if(ack)ack({rooms:openPublicRoomsList()})});socket.on('joinRoom',({code,maxPlayers,token}={},ack)=>{if(!roomOpLimitOk(socket)){if(ack)ack({ok:!1,error:'rate-limited'});return}
code=String(code||'').slice(0,20).toUpperCase();const room=rooms.get(code);if(!room){if(ack)ack({ok:!1,error:'not-found'});return}
touch(room);if(socket.data.roomCode===code&&socket.data.slot!==null&&socket.data.slot!==undefined){const mine=room.players[socket.data.slot];if(mine&&mine.connected){if(ack)ack({ok:!0,slot:socket.data.slot,mode:room.mode,token:mine.token,t:Date.now()});return}}
const limit=room.maxPlayers||maxPlayersForMode(normalizeMode(room.mode));if(token){for(let i=0;i<limit;i++){const existing=room.players[i];if(existing&&tokensMatch(existing.token,token)){existing.connected=!0;existing.leftAt=null;existing.socketId=socket.id;assignSocketToSlot(socket,code,i);if(ack)ack({ok:!0,slot:i,mode:room.mode,token,t:Date.now()});broadcastPresence(code);return}}}
let slot=-1;for(let i=0;i<limit;i++){if(!room.players[i]){slot=i;break}}
if(slot===-1){if(ack)ack({ok:!1,error:'full'});return}
const newToken=crypto.randomBytes(16).toString('hex');room.players[slot]={token:newToken,joinedAt:Date.now(),connected:!0,leftAt:null,socketId:socket.id};assignSocketToSlot(socket,code,slot);if(ack)ack({ok:!0,slot,mode:room.mode,token:newToken,t:Date.now()});broadcastPresence(code)});socket.on('getPresence',(_data,ack)=>{const code=socket.data.roomCode;const room=code?rooms.get(code):null;if(room)touch(room);if(ack)ack({players:room?presenceSnapshot(room):{}})});socket.on('roomMessage',({payload}={})=>{const code=socket.data.roomCode;const slot=socket.data.slot;if(!code||slot===null||slot===undefined||!rooms.has(code))return;if(!rateLimitOk(socket))return;if(!payloadSizeOk(payload))return;const room=rooms.get(code);touch(room);room.seqBySlot=room.seqBySlot||{};room.seqBySlot[slot]=(room.seqBySlot[slot]||0)+1;const mySeq=room.seqBySlot[slot];if(payload&&payload.type==='request-state'){const others=Object.keys(room.players).filter(s=>Number(s)!==slot&&room.players[s].connected);if(others.length===0&&room.lastCheckpoint){socket.emit('stateFallback',{state:room.lastCheckpoint.state});return}}
socket.to('room:'+code).emit('roomMessage',{from:slot,t:Date.now(),seq:mySeq,payload})});socket.on('checkpoint',({state}={})=>{const code=socket.data.roomCode;const slot=socket.data.slot;if(!code||slot===null||slot===undefined||!rooms.has(code)||!state)return;if(!payloadSizeOk(state))return;const room=rooms.get(code);touch(room);room.lastCheckpoint={state,bySlot:slot,t:Date.now()}});socket.on('leaveRoom',()=>handleLeave(socket));socket.on('disconnect',()=>handleLeave(socket))});app.get('/',(req,res)=>{res.type('text/plain').send('Route9 game server is running.')});setInterval(()=>{const cutoff=Date.now()-3*60*60*1000;for(const[code,room]of rooms.entries()){const anyConnected=Object.values(room.players).some(p=>p.connected);if(anyConnected)continue;if((room.lastActivity||room.createdAt)<cutoff)rooms.delete(code);}},30*60*1000);const SELF_URL=process.env.RENDER_EXTERNAL_URL||process.env.SELF_URL||null;if(SELF_URL){setInterval(()=>{try{https.get(SELF_URL,(res)=>{res.resume()}).on('error',()=>{})}catch(e){}},4*60*1000)}
server.listen(PORT,()=>{console.log('Route9 game server listening on port '+PORT)})